grub netboot implementation
hpcng/warewulf pull request #859
Opened 2023-06-21 15:44 UTC by mslacken

added a simple grub.cfg in order to replace iPXE

2023-10-11 16:05 UTC, anderbubble commented
I'm reviewing this now, and rebased against current origin/development to resolve conflicts.

2023-10-11 18:34 UTC, anderbubble requested changes
Forgive the long-winded review here: I have a lot of things.

I don't like that this implementation makes the default profile special, and restricts what you can do with it. (To summarize: grub boot needs an EFI shim, and this implementation assumes to get it from the container assigned to the default profile.)

My first thought was "why get it from the container at all?" After all, the grub boot shim isn't that different from the ipxe bootloader: today we package that with Warewulf, but we're planning (#784) to stop doing that, in favor of using the ipxe packages included with, say, Suse or Rocky. Rocky has a similar shim package (`shim-x64`) for grub, and I presume Suse does, too; so why can't we just use that, and leave the container alone?

I _think_ the answer is secure boot: it's not enough to have a "working" shim; we need a shim that has keys to validate that the eventual grub, kernel, etc is valid. So we really do need the shim that's in the container, not just any old shim.

But, if so, I think that means that this implementation, of just using the shim from the container of the default profile, is insufficient: what if we want to be able to provision two different operating systems that have incompatible requirements for the boot shim?

If my understanding is correct, I think this needs to work pretty much exactly how kernels work today: if you're doing a grub boot, the shim should be detected at boot time and fed from the container that it's about to boot, without having to copy the shim somewhere or treat any specific container special. (I haven't looked in depth regarding how kernel auto-detection works yet, so I presume it's more complex than that; but the end result is the same: Warewulf doesn't use the kernel from the container of the default profile; it uses the kernel from the container it's booting.)

This analogy may extend to the ability to import shims _into_ warewulf, like how we support importing kernels into warewulf and specifying them explicitly; but I expect it's less necessary to support arbitrary shims per container. (i.e., it doesn't appear to be normal to have multiple versions of the shim installed in the container)

To summarize, I think the following changes should be made:

* Don't treat the default profile specially, or introduce any new limitations on in
* Read the shim dynamically from the container being booted in the same way that we read the kernel from the container

2023-10-12 03:08 UTC, anderbubble commented
@mslacken thanks for reminding me in the meeting today that the use of the default container is only for the node discovery case / unknown node case.

In this case, could we just use the shims from the host operating system?

2023-10-12 05:08 UTC, mslacken commented
Using the shim and grub of the host is also possible and maybe the better alternative.

2023-10-14 09:10 UTC, anderbubble requested changes

2023-10-14 09:10 UTC, anderbubble commented on CHANGELOG.md
> +- first container imported container is added to the default profile
If this is using the host shim now, can all the special-casing around the default profile and its container be removed?

2023-10-23 23:50 UTC, anderbubble requested changes
- It looks like the commit history contains the previous implementation attempt that is later undone. I'd prefer a clean commit history; but I understand that the best way to do that is not particularly intuitive. I have a method I got from a friend; but perhaps I should get that method published before I hold people accountable to it.
- It looks like there's still some special-casing of the default profile left behind from the first implementation attempt.
- If I understand correctly that `sentDB` is entirely for the purpose of the test suite, I really think it should be removed and behavior should be validated some other way during testing. Code should be written so as to be testable; but not by introducing global state to the main application.
- Other things. (See individual comments.)

2023-10-23 23:50 UTC, anderbubble commented on internal/pkg/warewulfd/warewulfd.go
> +}
This is probably fine; but maybe it should only filter out for calls to `http://efiboot//`?

2023-10-23 23:50 UTC, anderbubble commented on internal/pkg/warewulfd/sentDB.go
Can you add a package-level comment about what sentDB is for? 

It looks to me like this is entirely for inspection during testing. Is that accurate? If so, I do not think this is how this should be tested. That each part has been sent should be verified by the test itself by acting as an http client and inspecting what is received.

Is warewulfd multi-threaded? The lock management here would seem to indicate so; but what happens if more than one node is being served at a time? Wouldn't that corrupt this global `sentDB` hash?

2023-10-23 23:50 UTC, anderbubble commented on internal/pkg/warewulfd/parser.go
> +	}
What if path_parts > 3 and stage == efiboot?

At least, "unknown path components in GET" probably needs to be adjusted. (It was probably inaccurate before, too.)

2023-10-23 23:50 UTC, anderbubble commented on internal/pkg/warewulfd/parser.go
> +	}
You don't need `if len(path_parts) > 3` here. `strings.Join(path_parts[2:], "/")` produces the desired output in both cases.

2023-10-23 23:50 UTC, anderbubble commented on internal/pkg/overlay/datastructure.go
> +	tstruct.ProfileMap, err = nodeDB.MapAllProfiles()
I don't see any overlays using ProfileMap. Why is it being added as part of this PR?

2023-10-23 23:50 UTC, anderbubble commented on internal/pkg/warewulfd/parser.go
> +		ret.hwaddr = ArpFind(ret.ipaddr)
ARP will only work if we're on the same Ethernet subnet as the target host. Is this usually encoded as hwaddr in GET? If not, I'm concerned by any dependence on ARP, as that would restrict Warewulf from being used behind a DHCP relay.

2023-10-23 23:50 UTC, anderbubble commented on internal/pkg/node/constructors.go
> +  boot method: ipxe
This is great (I was requesting a generic "boot method" or "bootloader" option, and a per-node setting, earlier; but is this actually used anywhere? I don't see `boot method` anywhere else in the code.

2023-10-23 23:50 UTC, anderbubble commented on internal/pkg/container/shim.go
I haven't put too much thought into it; but it seems like shim.go and grub.go could be genericized and combined a bit.

2023-10-24 17:32 UTC, mslacken commented on internal/app/wwctl/container/imprt/main.go
> +	}
No its not obsolete as this makes it easier for newbies to get in touch with warewulf. And the fist container is *always* the default one.

2023-10-24 17:33 UTC, mslacken commented on internal/app/wwctl/profile/delete/main.go
> +	}
Still do the special case or we will have to remove the switch`--setdefault` for `container import`.

2023-10-24 17:42 UTC, mslacken commented on internal/pkg/api/profile/profile.go
> +	}
No debugging but it checks that we can unmarshall the var `set.NodeYaml`, but the check is duplicated so we can remove.

2023-10-24 18:51 UTC, mslacken commented
> * It looks like the commit history contains the previous implementation attempt that is later undone. I'd prefer a clean commit history; but I understand that the best way to do that is not particularly intuitive. I have a method I got from a friend; but perhaps I should get that method published before I hold people accountable to it.
>

I know having a clean commit history looks good and professional, but leaving the dead ends in the commits also shows that the authors tries alternative methods and that this methods failed. A null result is also a result. Or are you a secret member of the TVA?
 
>     * It looks like there's still some special-casing of the default profile left behind from the first implementation attempt.
> 
We have special casing for the default profile which can't removed right now, e.g. `container import --setdefault`. The code added here just makes this more obvious. 
>     * If I understand correctly that `sentDB` is entirely for the purpose of the test suite, I really think it should be removed and behavior should be validated some other way during testing. Code should be written so as to be testable; but not by introducing global state to the main application.
> 
As explained below, the sentDB isn't used right now, but will be used in the future for measured boot. I want to leave it int he code base right, as if it resides not in development branch the work may get lost.
>     * Other things. (See individual comments.)
I wlll update the PR

2023-12-19 07:48 UTC, JasonYangShadow commented on internal/pkg/warewulfd/sentDB.go
> +	sentDB = map[string]*SentFiles{}
not sure the current use case falls into the usage of sync.map
https://pkg.go.dev/sync#Map
 (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or 
 (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.

2023-12-19 07:52 UTC, JasonYangShadow commented on internal/pkg/warewulfd/util.go
> +	_, err = fd.Seek(0, 0)
might use fd.Seek(0, io.SeekStart) for a better understanding here.

2023-12-21 08:04 UTC, JasonYangShadow commented
lgtm! I do not have more comments. Thanks for the hard work.

2023-12-21 08:28 UTC, mslacken commented
@JasonYangShadow  can you just approve, so that I can merge?

2023-12-21 08:29 UTC, JasonYangShadow approved these changes

2023-12-21 08:32 UTC, JasonYangShadow commented
@anderbubble I do not have more comments. It's up to other community members to approve if it's okay to be merged or not. cc @mslacken

2023-12-24 02:23 UTC, anderbubble commented
Rebased to main to continue testing and see if the checks clear.

2023-12-24 04:04 UTC, anderbubble reviewed
I haven't been able to boot my node with Grub yet. What am I doing wrong?

2023-12-24 04:04 UTC, anderbubble commented on CHANGELOG.md
> +- grub in combination can now be set as boot method with `warewulf.grubboot: true` in
I set this in `warewulf.conf`

```
warewulf:
  port: 9873
  secure: false
  update interval: 60
  autobuild overlays: true
  host overlay: true
  syslog: false
  grubboot: true
```

But I still got an iPXE boot. What did I do wrong? (I also restarted warewulfd.)

2023-12-24 04:05 UTC, anderbubble commented on CHANGELOG.md
> +- grub in combination can now be set as boot method with `warewulf.grubboot: true` in
I realized that I hadn't rebuilt the dhcp config. Now I've done that and am at least getting an error. Investigating.

2023-12-24 05:17 UTC, anderbubble commented on CHANGELOG.md
> +- grub in combination can now be set as boot method with `warewulf.grubboot: true` in
I fixed a couple errors in the dhcp template, but I still don't have grub booting successfully.

<img width="1392" alt="Screenshot 2023-12-23 at 10 16 21 PM" src="https://github.com/hpcng/warewulf/assets/350294/df4ca60b-38ca-4c1b-af01-013efe03cd9f">

I don't think my "fixes" are the cause of the issue; but let me know if you see what I'm doing wrong. @mslacken

2023-12-24 05:44 UTC, anderbubble commented on CHANGELOG.md
> +- grub in combination can now be set as boot method with `warewulf.grubboot: true` in
I didn't have grub or shim installed in the container, but only the host. But after installing that, still no change.

2023-12-24 06:00 UTC, anderbubble commented on CHANGELOG.md
> +- grub in combination can now be set as boot method with `warewulf.grubboot: true` in
The documented grub package to be installed was incorrect: should be `grub2-efi-x64`.

I'm further now: still not a successful boot, though.

<img width="1392" alt="Screenshot 2023-12-23 at 10 59 22 PM" src="https://github.com/hpcng/warewulf/assets/350294/f9498450-11d3-48b0-a995-4cae27eaf28c">

2023-12-24 06:08 UTC, anderbubble commented on CHANGELOG.md
> +- grub in combination can now be set as boot method with `warewulf.grubboot: true` in
<img width="692" alt="Screenshot 2023-12-23 at 11 08 30 PM" src="https://github.com/hpcng/warewulf/assets/350294/aefe4fa5-9190-4d3e-8bba-e09e733dab05">

2024-01-10 15:06 UTC, mslacken commented
@anderbubble I have now tested the code again and found that there is a timeout which grub can't handle, if 
1. the overlays are not readily available
2. the container image isn't built
as then warewuld isn't sending out the images in the right timeframe. I think we don't see this behavior for iPXE as there, if the compressed couldn't be fetched, iPXE makes a failover to uncompressed images, which gives warewulfd enough time to build them.
So in order to use the grub boot you will have to run `wwctl overlay /container build` before boot.

I was also able to boot the rocky image from a openSUSE ww4-host.

2024-01-12 08:06 UTC, JasonYangShadow commented on CHANGELOG.md
> +- grub in combination can now be set as boot method with `warewulf.grubboot: true` in
I have a similar scrrenshot
![image](https://github.com/hpcng/warewulf/assets/2051711/15143253-9085-40c5-8a12-9e04fca85332)
![image](https://github.com/hpcng/warewulf/assets/2051711/81727a44-c1ca-4f32-84c3-8dfedff6a648)

2024-01-12 08:14 UTC, JasonYangShadow commented
oh, confirmed that 
https://github.com/hpcng/warewulf/pull/859#discussion_r1450008563
issue listed here, can be temporally resolved by
```
wwctl container build --force NAME
wwctl overlay build
wwctl server restart
```
my local compute nodes can successfully pass `kernel panic` issue and continue.

2024-01-18 02:24 UTC, anderbubble commented
@mslacken I made a couple changes that ordinarily I'd want to ask you about; but I think by this point you're more interested in getting this merged than anything, so I'm going to go ahead and do that. Of course, if you disagree with any of my changes we can do a different (presumably smaller, easier) PR.

2024-01-18 02:25 UTC, anderbubble approved these changes

2024-01-18 02:25 UTC, merged